// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Signal$BkonkleSignal = require("./Signal.bs.js");

function make(value) {
  return {
          signal: Signal$BkonkleSignal.constant(value)
        };
}

function send(value, channel) {
  return Signal$BkonkleSignal._set(value, channel.signal);
}

function signal(channel) {
  return channel.signal;
}

var channel = make;

exports.make = make;
exports.channel = channel;
exports.send = send;
exports.signal = signal;
/* No side effect */
