// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Signal$BkonkleSignal = require("./Signal.bs.js");

var $$window = window;

function keyPressed(keyCode) {
  var out = Signal$BkonkleSignal.constant(false);
  $$window.addEventListener("keydown", (function (e) {
          if (e.keyCode === keyCode) {
            return Signal$BkonkleSignal._set(true, out);
          } else {
            return 0;
          }
        }));
  $$window.addEventListener("keyup", (function (e) {
          if (e.keyCode === keyCode) {
            return Signal$BkonkleSignal._set(false, out);
          } else {
            return 0;
          }
        }));
  return out;
}

function mouseButton(button) {
  var out = Signal$BkonkleSignal.constant(false);
  $$window.addEventListener("mousedown", (function (e) {
          if (e.button === button) {
            return Signal$BkonkleSignal._set(true, out);
          } else {
            return 0;
          }
        }));
  $$window.addEventListener("mouseup", (function (e) {
          if (e.button === button) {
            return Signal$BkonkleSignal._set(false, out);
          } else {
            return 0;
          }
        }));
  return out;
}

function mouseButtonPressed(button) {
  if (button >= 3) {
    return mouseButton(2);
  } else {
    switch (button) {
      case /* Left */0 :
          return mouseButton(0);
      case /* Middle */1 :
          return mouseButton(2);
      case /* IE8Middle */2 :
          return mouseButton(4);
      
    }
  }
}

exports.$$window = $$window;
exports.keyPressed = keyPressed;
exports.mouseButton = mouseButton;
exports.mouseButtonPressed = mouseButtonPressed;
/* window Not a pure module */
